services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins.local
    ports:
    - "8081:8080"
    volumes:
    - jenkins-data:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
