pipeline {
  agent any

  stages {
    stage('Build image') {
      steps {
        script {
          def dockerImage = "rbsilmann/apache-cache-container:${env.BRANCH_NAME ?: 'latest'}"
          env.DOCKER_IMAGE = dockerImage
          docker.build(env.DOCKER_IMAGE, "ci/jenkins/apache-cache-container")
        }
      }
    }

    stage('Push image') {
      steps {
        script {
          docker.withRegistry('https://registry-1.docker.io/', 'credentials-id') {
            docker.image(env.DOCKER_IMAGE).push()
          }
        }
      }
    }
  }
}